# ---------------------------------------------------
# Étape 1 : Étape de test avec toutes les dépendances
# ---------------------------------------------------
FROM node:18-alpine AS test

WORKDIR /app

# Copier tous les fichiers sources de l’application
COPY . .

# Installer toutes les dépendances (prod + dev)
RUN yarn install --frozen-lockfile

# Fichier .env spécifique pour les tests (SQLite par défaut ici)
COPY .env.test .env

# Argument pour choisir quels tests exécuter
ARG TEST_SCOPE=all
ENV NODE_ENV=test
ENV LOG_LEVEL=debug
# Exécution conditionnelle des tests
ARG TEST_RUN_TAG=none  # 👈 ceci sert à invalider le cache
# Afficher les tests disponibles
RUN yarn test:unit:build --listTests --silent=false --colors --detectOpenHandles

# Exécuter les bons tests en fonction de TEST_SCOPE
RUN echo "🧪 Test run tag: $TEST_RUN_TAG" && \
    if [ "$TEST_SCOPE" = "integration" ]; then \
      echo "🔍 Intégration uniquement (SQLite)" && \
      yarn test:integration:test --verbose --silent=false --colors --detectOpenHandles ; \
    elif [ "$TEST_SCOPE" = "fail" ]; then \
      echo "💥 Test KO volontaire" && \
      yarn test:unit:fail --verbose --silent=false --colors --detectOpenHandles  ; \
    else \
      echo "✅ Unitaires + Intégration SQLite" && \
      yarn test:unit:build --verbose --silent=false --colors --detectOpenHandles && \
      yarn test:integration:test --verbose --silent=false --colors --detectOpenHandles; \
    fi


