version: '3.8'
services:
  mysql-staging:
    image: mysql:8.0
    container_name: mysql-staging
    restart: unless-stopped
    env_file: .env.staging
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD} # par défaut identique au root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  simple-todo-staging:
    container_name: simple-todo-staging
    build:
      context: .
      dockerfile: Dockerfile.staging
      target: staging
      args:
        TEST_SCOPE: ${TEST_SCOPE}
        TEST_RUN_TAG: ${TEST_RUN_TAG}
    depends_on:
      mysql-staging:
        condition: service_healthy
    env_file: .env.staging
